### ISSUE TITLE
Switch to Ubuntu 16.04

### ISSUE THREAD

**Issue by ComMouse** [at15/lnmp#12]
RT @at15 

Update by @at15

- [x] Drop PHP support for 14.04, that is 16.04 will only have PHP7 https://github.com/at15/lnmp/tree/legacy/ubuntu-14.04-PHP5
- [x] Switch to Ansible instead of raw shell script #13

**Comment by at15** [comment]
so what's the point about switching to 16.04 since we are using ppa? I haven't wrote PHP for a while, so /w\

**Comment by at15** [comment]
@ComMouse also, PHP7 or 5 or both?

**Comment by at15** [comment]
oops, PHP5 is gone for 16.04, so stick to 14.04 for 5, or use a PPA for PHP5?

**Comment by at15** [comment]
btw: @ComMouse I think we should transfer this project to dongyue's namespace instead of mine, or make a fork of it.

**Comment by ComMouse** [comment]
PPA is a must for PHP installation since the official version is always not the latest

**Comment by ComMouse** [comment]
also @at15 If the box needs to be migrated into dyweb group, why not change a nicer name? like rotunda or something else :XD

**Comment by at15** [comment]
e... you can do that after make the fork, just wait before I finish the migration to ansible. And also you need a new account for [vagrantcloud](https://atlas.hashicorp.com/boxes/search?utm_source=vagrantcloud.com&vagrantcloud=1) to publish the box.

**Comment by at15** [comment]
@ComMouse you can have a look now, the upload should be finished when you noticed the message.

**Comment by ComMouse** [comment]
@JasonQSY Have a look?

**Comment by JasonQSY** [comment]
@ComMouse Is it enough to just check the box environment?

**Comment by ComMouse** [comment]
@JasonQSY Try deploying a website or Laravel?

**Comment by JasonQSY** [comment]
Try it on `cure-web` based on `Laravel`. Some suggestions and problems.

1. The network is very bad. Maybe add 'try to `vagrant reload --provision` if the download fails' in doc.
2. Since most of our projects use `composer` and the box has already had `npm`, I think it is not a bad idea to add `composer` globally. For example,
```bash
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer
```
3. `npm install` fails for `cure-web` on my computer (Windows 10). I'm not very clear about the reason. Maybe it is the window-host/linux guest problem. See also <https://github.com/npm/npm/issues/5874>. Working on it currently.
4. How to have access to `phpmyadmin` on host machine? Maybe add a forwarded port?
5. `redis-server` start normally but haven't been tested.

Only 3 is fatal. Maybe test it on another machine.

@at15 @ComMouse

**Comment by at15** [comment]
1. you should not be using the provision if your network is bad, use the pre-built box.
2. It used to have composer, I forget to add it,you forget to add `chmod`
3. do you run npm install in host or guest? composer also have the similar symbolic link problem. 
4.  I mentioned in readme you should use `mysql.lk:8080` if you forward guest 80 to host 8080, I will put a `Vagrantfile` example in readme.
5. I tested it with the command line, get and set works fine

**Comment by at15** [comment]
I have updated ansible config, and is uploading the new box for version 1.0.1, you can build from the source if you like, some problems and solutions are addressed in readme, and after this issue is finished, I think it's time to transfer its ownership to dyweb or make a fork, whatever you like, leave this to you guys.

**Comment by JasonQSY** [comment]
Yes, I believe there is only the symlink problem and others work fine now.

LGTM @ComMouse

**Comment by ComMouse** [comment]
@at15 Consider use private ips for exposed sites, like the config in Homestead and Rotunda (`tongqu-web/script/ops/Vagrantfile`)

**Comment by ComMouse** [comment]
@JasonQSY npm should be installed outside vagrant. Due to symlink problem, installing in vagrant would definitely fail (VirtualBox mount not works well for symbolic link now)

**Comment by at15** [comment]
@ComMouse yeah it is possible, but my new quarter is going to begin next week and I have interview this Friday, so, 这个锅就甩给你们了.....

**Comment by JasonQSY** [comment]
Life is short, I choose mac 😕

**Comment by at15** [comment]
@JasonQSY 1 mac = 1 win+linux laptop + 1 PC with 2 monitor
